openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8000
  description: Generated server url
paths:
  /lectors:
    put:
      tags:
      - lecturer-controller
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LecturerDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LecturerDto'
  /group:
    put:
      tags:
      - group-controller
      operationId: update_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GroupDto'
  /disciplines:
    get:
      tags:
      - discipline-controller
      operationId: getAll_3
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DisciplineDto'
    put:
      tags:
      - discipline-controller
      operationId: update_2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisciplineDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
    post:
      tags:
      - discipline-controller
      operationId: createNewDiscipline
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisciplineDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "201":
          description: Created
  /classtime:
    put:
      tags:
      - class-time-controller
      operationId: update_3
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassTimeDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClassTimeDto'
  /classroom:
    put:
      tags:
      - classroom-controller
      operationId: update_4
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassroomDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClassroomDto'
  /admin:
    get:
      tags:
      - admin-controller
      operationId: getAdminPage
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
      - admin-controller
      operationId: createNewClassroom
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassroomDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "201":
          description: Created
  /records/{id}:
    get:
      tags:
      - record-controller
      operationId: get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RecordDto'
  /records/all:
    get:
      tags:
      - record-controller
      operationId: getAll
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecordDto'
  /lectors/{id}:
    get:
      tags:
      - lecturer-controller
      operationId: get_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LecturerDto'
  /lectors/all:
    get:
      tags:
      - lecturer-controller
      operationId: getAll_1
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LecturerDto'
  /group/{id}:
    get:
      tags:
      - group-controller
      operationId: get_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GroupDto'
  /group/specialization:
    get:
      tags:
      - group-controller
      operationId: getBySpecialization
      parameters:
      - name: specialization
        in: query
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupDto'
  /group/degree:
    get:
      tags:
      - group-controller
      operationId: getByDegree
      parameters:
      - name: degree
        in: query
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupDto'
  /group/all:
    get:
      tags:
      - group-controller
      operationId: getAll_2
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupDto'
  /disciplines/{id}:
    get:
      tags:
      - discipline-controller
      operationId: get_3
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DisciplineDto'
    delete:
      tags:
      - discipline-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
  /classtime/{id}:
    get:
      tags:
      - class-time-controller
      operationId: get_4
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClassTimeDto'
  /classtime/all:
    get:
      tags:
      - class-time-controller
      operationId: getAll_4
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClassTimeDto'
  /classroom/{id}:
    get:
      tags:
      - classroom-controller
      operationId: get_5
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClassroomDto'
  /classroom/all:
    get:
      tags:
      - classroom-controller
      operationId: getAll_5
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClassroomDto'
components:
  schemas:
    LecturerDto:
      type: object
      properties:
        lecturerId:
          type: integer
          format: int32
        name:
          type: string
        surname:
          type: string
        middlename:
          type: string
    GroupDto:
      type: object
      properties:
        id:
          type: string
        isLecture:
          type: boolean
        specialization:
          type: string
        degree:
          type: string
        course:
          type: integer
          format: int32
        groupNumber:
          type: integer
          format: int32
        lecturerId:
          type: integer
          format: int32
    DisciplineDto:
      type: object
      properties:
        disciplineId:
          type: integer
          format: int32
        name:
          type: string
        lecturerId:
          type: integer
          format: int32
    ClassTimeDto:
      type: object
      properties:
        classTimeId:
          type: integer
          format: int32
        classDate:
          type: string
          format: date
        classTime:
          $ref: '#/components/schemas/LocalTime'
        weekNumber:
          type: integer
          format: int32
    LocalTime:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        minute:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
        nano:
          type: integer
          format: int32
    ClassroomDto:
      type: object
      properties:
        classroomId:
          type: integer
          format: int32
        name:
          type: string
        capacity:
          type: integer
          format: int32
    RecordDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        disciplineId:
          type: integer
          format: int32
        classTimeId:
          type: integer
          format: int32
        groupId:
          type: string
        classroomId:
          type: integer
          format: int32
        lecturerId:
          type: integer
          format: int32
